name: 'sandbox'
version: 0.0.1
description: A web app built using polymer.dart.
#author: Your Name <email@example.com>
#homepage: https://www.example.com
dependencies:
  polymer: ^0.17.0
  web_components: ^0.12.0
  browser: any
  polymer_elements:
    git:
      url: https://github.com/dart-lang/polymer_elements.git
transformers:
- web_components:
    entry_points:
    - web/index.html
- $dart2js:
    minify: true
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
environment:
  sdk: ">=1.2.0 <2.0.0"

dependency_overrides:
  polymer:
    git:
      ref: 0.17-0-dev-interop-reverse
      url: https://github.com/dart-lang/polymer-dart.git
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git
